#!/usr/bin/env bash

GCC_VERSION="ia16"
ISL_VERSION=0.15

GCC_CONFIGURE_OPTIONS="--disable-plugin
                       --enable-lto
                       --disable-libstdcxx-dual-abi
                       ${GCC_CONFIGURE_OPTIONS}"
