#!/usr/bin/env bash

export GCC_VERSION="ia16"

export GCC_CONFIGURE_OPTIONS="--disable-plugin
                              --enable-lto
                              --disable-libstdcxx-dual-abi
                              ${GCC_CONFIGURE_OPTIONS}"
